-- 073_service_copy.sql
-- A description and benefits for every active service (all branches), so
-- GlowSync AI and the Services page guide can promote each one. Matched by
-- category + name. Safe to run again; it only rewrites these two fields.

update branch_services bs
set description = v.description,
    benefits = v.benefits
from (values
  ('Body & Wellness', 'Bikini', 'Gentle waxing of the bikini line for a clean, smooth finish that lasts for weeks.', 'Smooth skin for up to 3-4 weeks, hair grows back finer over time, perfect before the beach or a special trip.'),
  ('Body & Wellness', 'Ear Candling', 'A soothing, relaxing ritual using warm hollow candles to help you unwind and feel refreshed.', 'Deeply calming and relaxing, a cozy add-on to any massage, a peaceful break from a busy day.'),
  ('Body & Wellness', 'Eyebrow', 'Quick waxing that cleans up stray brow hairs for a neat, polished look.', 'Instantly cleaner brows, frames the face, lasts longer than shaving or plucking.'),
  ('Body & Wellness', 'Foot Massage', 'A relaxing massage for tired feet that eases tension after a long day of standing or walking.', 'Relieves tired, aching feet, improves circulation, helps you relax and sleep better.'),
  ('Body & Wellness', 'Hand Massage', 'A soothing massage for hands and wrists that melts away stiffness and stress.', 'Eases stiffness from typing and daily work, improves circulation, leaves hands soft and relaxed.'),
  ('Body & Wellness', 'UnderArm', 'Underarm waxing for smooth, hair-free underarms that last for weeks.', 'Smooth underarms for up to 3-4 weeks, no stubble or shadows, hair grows back finer over time.'),
  ('Body & Wellness', 'Upper Lip', 'Quick upper-lip waxing for a clean, smooth look.', 'Removes fine and dark hairs from the root, smooth for weeks, makeup goes on more smoothly.'),
  ('Brows & Lashes', 'AirLashes', 'Feather-light lash extensions for fuller, longer lashes that still feel natural.', 'Wake up with beautiful lashes, lightweight and comfortable, skip mascara for weeks.'),
  ('Brows & Lashes', 'Brow Shaping', 'Expert shaping that gives your brows a clean, balanced shape that suits your face.', 'Brows that frame your face, a neater and more put-together look, quick and affordable.'),
  ('Brows & Lashes', 'Brow Threading', 'Precise threading that shapes brows hair by hair for clean, defined lines.', 'Very precise shape, gentle on sensitive skin, no chemicals or wax.'),
  ('Brows & Lashes', 'Cat-eye Lashes', 'Lash extensions styled longer at the outer corners for a lifted, flirty cat-eye look.', 'Instantly lifted, glamorous eyes, perfect for events and photos, no daily mascara or falsies.'),
  ('Brows & Lashes', 'Eyelash lift', 'A lash lift that curls and lifts your own natural lashes, no extensions needed.', 'Naturally curled, longer-looking lashes for weeks, low maintenance, eyes look more open and awake.'),
  ('Brows & Lashes', 'Eyeliner', 'Semi-permanent eyeliner that defines your eyes so you wake up ready.', 'Defined eyes every day, saves time on makeup, smudge-proof and long-lasting.'),
  ('Brows & Lashes', 'Hair & Make-up', 'Professional hair styling and make-up for weddings, debuts, photoshoots and special events.', 'Look camera-ready and confident, long-lasting finish, styled to suit your face and outfit.'),
  ('Brows & Lashes', 'Ombre Brows', 'Semi-permanent ombre brows with a soft powdered look, light at the front and defined at the tail.', 'Perfect brows every morning, natural soft-makeup effect, saves time and lasts long.'),
  ('Cocktail Drips', 'AGE REVIVE', 'An anti-aging IV drip with Collagen, Placenta, Vitamin C, Biotin and Thioctic Acid.', 'Supports firmer, more youthful-looking skin, helps skin glow from within, supports healthy hair and nails.'),
  ('Cocktail Drips', 'Collagen', 'A collagen drip that supports your skin from the inside.', 'Supports skin elasticity and hydration, helps skin look plumper and smoother, a boost for healthy hair and nails.'),
  ('Cocktail Drips', 'CRYSTAL DETOX', 'A detox drip with Vitamin B Complex (B1, B6, B12), Collagen and Glutathione.', 'Helps you feel refreshed and energized, supports a brighter complexion, a great reset after stressful weeks.'),
  ('Cocktail Drips', 'GLUTA IV PUSH', 'A quick Glutathione and Vitamin C push, our most popular glow booster.', 'Helps brighten and even out skin tone, antioxidant boost, quick and affordable.'),
  ('Cocktail Drips', 'IMMUNE BOOST', 'An immune-support drip with Vitamin C and Vitamin B Complex.', 'Supports your immune system, helps fight tiredness, great during flu season or before travel.'),
  ('Cocktail Drips', 'META SLIM', 'A slimming drip with Lipo-1, L-Carnitine and Vitamin B Complex to support your weight goals.', 'Supports fat metabolism, helps boost energy, best paired with diet, exercise or our slimming treatments.'),
  ('Cocktail Drips', 'Nuwhite', 'A whitening drip that helps you achieve brighter, more even skin.', 'Helps brighten dull skin, supports a more even skin tone, antioxidant care from within.'),
  ('Cocktail Drips', 'Placenta', 'A placenta drip known for skin renewal and rejuvenation.', 'Supports skin renewal, helps skin look fresher and younger, a nourishing boost for tired skin.'),
  ('Cocktail Drips', 'POWER WHITE', 'Our strongest whitening drip with a high dose of Glutathione, Vitamin C and Alpha Lipoic Acid.', 'Helps visibly brighten and even out skin tone, powerful antioxidant protection, for faster glow results.'),
  ('Cocktail Drips', 'Vitamin B', 'A Vitamin B shot that helps fight fatigue and supports your energy.', 'Helps boost energy, supports a healthy metabolism and nerves, great for busy, tired days.'),
  ('Cocktail Drips', 'Vitamin C', 'A Vitamin C shot for glowing skin and stronger immunity.', 'Supports immunity, helps brighten skin, antioxidant protection, very affordable.'),
  ('Doctor''s Procedure', 'Alartox', 'A doctor-administered botox treatment that helps reduce nose flaring for a slimmer-looking nose.', 'Helps the nose look smaller when smiling, quick with no downtime, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Barbie Arms', 'A doctor-administered botox treatment that helps slim and contour the upper arms.', 'Helps arms look slimmer and more toned, no surgery, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Calftox', 'A doctor-administered botox treatment that helps slim bulky calf muscles.', 'Helps legs look longer and slimmer, no surgery or downtime, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Cheek Filler', 'Dermal filler that restores volume and lift to the cheeks.', 'Fuller, lifted cheeks, a more youthful contour, instant results, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Chin Filler', 'Dermal filler that defines and projects the chin for a more balanced profile.', 'Better-defined chin and jawline, a more balanced side profile, instant results, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Forehead Filler', 'Dermal filler that smooths and rounds a flat or hollow forehead.', 'Softer, smoother forehead shape, a more youthful look, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Hiko Nose Thread Lift', 'A non-surgical nose lift using dissolvable threads to raise and define the nose bridge.', 'Higher, more defined nose without surgery, quick procedure with minimal downtime, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Jawtox', 'A doctor-administered botox treatment that slims the jaw muscles for a V-shaped face.', 'Slimmer, softer jawline, can help ease teeth clenching, no surgery, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Lip Filler', 'Dermal filler that adds volume, shape and definition to the lips.', 'Fuller, well-shaped lips, natural-looking results, instant effect, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Mole Removal', 'Removal of unwanted moles by our licensed doctor after an assessment.', 'Clearer, smoother skin, quick procedure, done safely by our licensed doctor.'),
  ('Doctor''s Procedure', 'Nose Filler', 'Dermal filler that lifts and shapes the nose bridge without surgery.', 'Higher nose bridge, instant results with no surgery, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Sclerotherapy', 'A doctor-administered treatment for spider veins on the legs.', 'Helps fade visible spider veins, smoother-looking legs, confidence to wear shorts and dresses.'),
  ('Doctor''s Procedure', 'Sweatox', 'A doctor-administered botox treatment that reduces excessive underarm sweating.', 'Helps keep underarms dry for months, no more sweat marks on clothes, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Temple Filler', 'Dermal filler that restores hollow temples for a fuller, younger-looking face.', 'Softer, more youthful face shape, balances the upper face, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Traptox', 'A doctor-administered botox treatment for the trapezius that gives a slimmer, longer-looking neck and shoulders.', 'Elegant neck and shoulder line, can help ease shoulder tension, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Under-eye Filler', 'Dermal filler that softens hollow, tired-looking under-eyes.', 'Look less tired, smoother under-eye area, a fresher and younger look, done by our licensed doctor.'),
  ('Doctor''s Procedure', 'Upper Face', 'Botox for the upper face: forehead lines, frown lines, crow''s feet and under-eye lines.', 'Smooths expression lines, a fresher and younger-looking face, quick with no downtime, done by our licensed doctor.'),
  ('Facial Services', 'Carbon Whitening Facial', 'A carbon laser facial that deep-cleans pores and gives an instant glow.', 'Helps brighten and even out skin tone, minimizes the look of pores, controls oiliness, instant glow.'),
  ('Facial Services', 'Deep Glow Facial', 'Our classic deep-cleansing facial that clears pores and refreshes dull, tired skin.', 'Deeply cleanses pores and removes impurities, leaves skin fresh and glowing, our most affordable facial.'),
  ('Facial Services', 'Galvanic Acne Treatment', 'An acne facial using gentle galvanic current to deep-clean pores and calm breakouts.', 'Helps clear clogged pores, calms active acne, helps prevent future breakouts.'),
  ('Facial Services', 'Glow Kit', 'A take-home skincare kit to keep your skin glowing between visits.', 'Helps maintain brighter skin at home, simple daily routine, makes your facial results last longer.'),
  ('Facial Services', 'Golden Glow Facial', 'An anti-aging facial that nourishes and firms skin for a radiant, golden glow.', 'Helps smooth fine lines, firmer and more radiant skin, perfect before special events.'),
  ('Facial Services', 'Keloid Injection', 'A doctor-administered injection that helps flatten and soften keloids (priced per ml).', 'Helps flatten raised keloids, softens and reduces itchiness, done by our licensed doctor.'),
  ('Facial Services', 'Korean Rose Facial', 'A Korean-inspired rose facial with deep moisture for that dewy glass-skin glow.', 'Deep moisture and a whitening effect, soft, dewy skin, calming and relaxing.'),
  ('Facial Services', 'Melasma Kit', 'A take-home skincare kit made for melasma and dark patches.', 'Helps lighten dark patches over time, supports a more even skin tone, easy daily routine.'),
  ('Facial Services', 'Pimple Cortisone Injection', 'A quick cortisone injection that shrinks a painful pimple fast (priced per ml).', 'Helps a big pimple go down within days, reduces pain and redness, great before an event.'),
  ('Facial Services', 'Signature Facial Peel', 'Our signature peel that gently removes dull top layers to reveal fresher skin.', 'Brighter, smoother skin, helps fade dark spots and acne marks, refines skin texture.'),
  ('Hair Services', 'Brazilian', 'A Brazilian smoothing treatment that tames frizz for soft, shiny, manageable hair.', 'Frizz-free, smoother hair, faster styling every day, shiny and soft finish.'),
  ('Hair Services', 'Coco Butter', 'A nourishing coco butter hair treatment for dry, damaged hair.', 'Deep moisture for dry hair, softer and shinier strands, helps repair damage.'),
  ('Hair Services', 'Hair Color', 'Professional hair coloring to refresh your look, from natural shades to bold colors.', 'A fresh new look, even, long-lasting color, expert shade matching for your skin tone.'),
  ('Hair Services', 'Hair Rebond', 'Hair rebonding for sleek, straight, low-maintenance hair.', 'Straight, smooth hair for months, less frizz, easy to style every morning.'),
  ('Hair Services', 'Loreal', 'A L''Oreal professional hair treatment that repairs and protects your hair.', 'Stronger, healthier-looking hair, more shine, protects color and treated hair.'),
  ('Laser Services', 'Beard', 'Laser hair reduction for the beard area for smoother skin with less shaving.', 'Less shaving and fewer ingrown hairs, smoother skin, long-term hair reduction over sessions.'),
  ('Laser Services', 'Brazilian', 'Laser hair reduction for the bikini area, a long-term alternative to waxing.', 'Long-term hair reduction, fewer ingrown hairs, smoother skin, less hassle than waxing.'),
  ('Laser Services', 'Elbow', 'A laser treatment that helps lighten dark elbows.', 'Helps lighten dark elbows, more even skin tone, confidence to wear sleeveless.'),
  ('Laser Services', 'Knee', 'A laser treatment that helps lighten dark knees.', 'Helps lighten dark knees, more even skin tone, confidence to wear shorts and skirts.'),
  ('Laser Services', 'Syringoma Removal', 'Laser removal of syringomas, the small bumps often found around the eyes.', 'Smoother skin around the eyes, quick procedure, a cleaner, fresher look.'),
  ('Laser Services', 'Tattoo Removal', 'Laser tattoo removal that fades unwanted ink over several sessions.', 'Fades tattoos gradually, safe for most skin types, a fresh start for your skin.'),
  ('Laser Services', 'Underarm', 'Laser hair reduction for the underarms, smoother than shaving.', 'Long-term hair reduction, helps reduce dark shadows from shaving, fewer ingrown hairs.'),
  ('Laser Services', 'Upper Lip', 'Laser hair reduction for the upper lip.', 'Long-term reduction of upper-lip hair, smoother skin, no more frequent waxing or threading.'),
  ('Laser Services', 'Warts / Skin Tag Removal', 'Laser removal of warts and skin tags.', 'Smoother, cleaner skin, quick procedure, no more snagging on clothes or jewelry.'),
  ('Nail Care', 'Foot Spa', 'A relaxing foot spa with soak, scrub and massage for soft, pampered feet.', 'Softens rough heels, relaxes tired feet, clean and well-groomed toes.'),
  ('Nail Care', 'Hand Spa', 'A pampering hand spa with soak, scrub and massage for soft, smooth hands.', 'Softer, smoother hands, relaxes tired hands, neat and healthy-looking nails.'),
  ('Nail Care', 'Ingrown Removal', 'Careful, hygienic removal of painful ingrown toenails.', 'Quick pain relief, helps prevent infection, done gently and hygienically.'),
  ('Nail Care', 'Manicure', 'A classic manicure with cleaning, shaping and polish for neat, pretty nails.', 'Clean, well-shaped nails, a polished look, affordable everyday pampering.'),
  ('Nail Care', 'Nail Extension Removal', 'Safe removal of nail extensions without damaging your natural nails.', 'Protects your natural nails, gentle and clean removal, ready for your next set.'),
  ('Nail Care', 'Pedicure', 'A classic pedicure with cleaning, shaping and polish for neat, pretty toes.', 'Clean, well-groomed toes, softer feet, sandal-ready in no time.'),
  ('Non-Surgical Liposuction', 'Arms', 'Non-surgical fat reduction and toning for the upper arms.', 'Helps slim and tone flabby arms, no surgery or downtime, confidence to go sleeveless.'),
  ('Non-Surgical Liposuction', 'Bra-line / Back', 'Non-surgical fat reduction for bra bulge and back fat.', 'Helps smooth bra-line bulges, a sleeker back, clothes fit better.'),
  ('Non-Surgical Liposuction', 'Double Chin', 'Non-surgical treatment that helps reduce a double chin and define the jawline.', 'Helps reduce chin fat, a sharper jawline, better photos with no surgery.'),
  ('Non-Surgical Liposuction', 'EmSculpt', 'EmSculpt muscle-building technology that tones muscles while you relax.', 'Helps build and tone muscles, firmer tummy or buttocks, like thousands of crunches in one session.'),
  ('Non-Surgical Liposuction', 'Exilift / Exilism', 'Radiofrequency and ultrasound treatment that tightens skin and reduces stubborn fat.', 'Firmer, tighter skin, helps reduce stubborn fat, no surgery or downtime.'),
  ('Non-Surgical Liposuction', 'Hips', 'Non-surgical fat reduction that helps contour the hips.', 'Smoother hip line, a more balanced figure, no surgery or downtime.'),
  ('Non-Surgical Liposuction', 'Love Handle', 'Non-surgical fat reduction for stubborn love handles.', 'Helps trim love handles, a smoother waistline, clothes fit better.'),
  ('Non-Surgical Liposuction', 'RadioFrequency (RF)', 'Radiofrequency treatment that heats deep layers to tighten skin and smooth contours.', 'Firmer, tighter skin, helps improve the look of cellulite, relaxing and no downtime.'),
  ('Non-Surgical Liposuction', 'Slimming Dome', 'A 30-minute slimming dome session that warms the body to help you sweat and detox.', 'Helps support slimming and detox, relaxing heat therapy, great with other slimming treatments.'),
  ('Non-Surgical Liposuction', 'Thigh', 'Non-surgical fat reduction that helps slim the thighs.', 'Slimmer-looking thighs, less inner-thigh rubbing, no surgery or downtime.'),
  ('Non-Surgical Liposuction', 'Tummy', 'Non-surgical fat reduction for a flatter-looking tummy.', 'Helps reduce belly fat, a flatter, smoother tummy, no surgery or downtime.'),
  ('Premium Treatments', 'Baby Face Ultra Lift Injection', 'A premium injectable treatment that lifts and firms for a fresh, baby-face look.', 'Lifts and firms the skin, stimulates collagen production, a younger-looking, glowing face.'),
  ('Premium Treatments', 'Dark Undereye Treatment', 'A premium treatment for dark circles and tired-looking eyes.', 'Brightens dark under-eye circles, stimulates natural collagen, you look more rested and fresh.'),
  ('Premium Treatments', 'Deep Acne Scar Treatment', 'A premium treatment that helps smooth deep acne scars.', 'Stimulates natural collagen and elastin production, helps smooth the look of acne scars, more even skin texture.'),
  ('Premium Treatments', 'Hair Restoration Treatment', 'A premium treatment for thinning hair and hair fall.', 'Stimulates natural hair growth, reduces hair shedding and hair fall, thicker, fuller-looking hair.'),
  ('Premium Treatments', 'Non-Surgical Hand Rejuvenation', 'A premium treatment that makes aging hands look younger.', 'Minimizes age spots and sun damage, improves skin hydration, smoother, younger-looking hands.'),
  ('Premium Treatments', 'Stretch Mark Treatment', 'A premium treatment that helps fade stretch marks.', 'Helps fade red and white stretch marks, stimulates collagen, smoother-looking skin.'),
  ('Slimming Services', 'Arms', 'A slimming treatment that helps tone and contour the arms.', 'Helps slim flabby arms, firmer, more toned look, no surgery.'),
  ('Slimming Services', 'Butt Lift', 'A non-surgical treatment that lifts and firms the buttocks.', 'Rounder, lifted look, firmer skin and muscles, no surgery or downtime.'),
  ('Slimming Services', 'Face', 'A face-slimming treatment that helps contour cheeks and jawline.', 'Slimmer, more defined face, a sharper jawline, no surgery.'),
  ('Slimming Services', 'Slimming Dome', 'A 60-minute slimming dome session that warms the body to help you sweat and detox.', 'Helps support slimming and detox, relaxing heat therapy, great with other slimming treatments.'),
  ('Slimming Services', 'Thighs', 'A slimming treatment that helps reduce and firm the thighs.', 'Slimmer, firmer-looking thighs, smoother skin, no surgery.'),
  ('Slimming Services', 'Tummy', 'A slimming treatment that helps reduce and firm the tummy.', 'Helps flatten the tummy, firmer skin, no surgery or downtime.'),
  ('Slimming Services', 'Tummy (Abs)', 'A muscle-toning treatment that helps sculpt your abs.', 'Helps tone and define the abs, firmer core, a great complement to diet and exercise.')
) as v(category, name, description, benefits)
where bs.category = v.category
  and bs.name = v.name;
